---
doctype:
  index
static:
  ./static
description:
  "ExaM | Главная страница"
title:
  "ExaM | Главная"
content:
  - contentitem:
      title: "Материалы для самоподготовки к аттестации в комиссии ТЭЦ"
      items:
        - i:
            href: ./tec14
            title: ТЭЦ-14
            description: "Первомайская ТЭЦ" 
            icon: svg/icons.svg#factory
            background: img/tec14.jpg
        - i:
            href: ./tec5
            title: ТЭЦ-5
            description: "Правобережная ТЭЦ"
            icon: svg/icons.svg#factory
            background: img/tec5.jpg
...